# python as calculator

In [1]:
# Addition, subtraction
print(5 + 5)
print(5 - 5)

# Multiplication, division, modulo, and exponentiation
print(3 * 5)
print(10 / 2)
print(18 % 7)
print(4 ** 2)

# How much is your $100 worth after 7 years?
print(100*1.1**7)

10
0
15
5.0
4
16
194.87171000000012


# variables

In [3]:
# Create a variable savings
savings = 100

# Create a variable growth_multiplier

growth_multiplier=1.1
# Calculate result

result=savings*growth_multiplier**7
# Print out result
print(result)

194.87171000000012


In [6]:
savings = 100
growth_multiplier = 1.1
desc = "compound interest"
# Create a variable profitable -bool
profitable=True

# Assign product of growth_multiplier and savings to year1
year1=savings*growth_multiplier

# Print the type of year1
print(year1)
print(type(year1))


# Assign sum of desc and desc to doubledesc
doubledesc=desc+desc

# Print out doubledesc
print(doubledesc)


110.00000000000001
<class 'float'>
compound interestcompound interest


# Lists

In [8]:
# working with lists
x=[1,2,3]
y=x
y[1]=8
print(x)
print(y)

[1, 8, 3]
[1, 8, 3]


In [10]:
x=[1,2,3]
y=x[:]     # y=list(x)
y[1]=8
print(x)
print(y)

[1, 2, 3]
[1, 8, 3]


In [11]:
# area variables (in square meters)
hall = 11.25
kit = 18.0
liv = 20.0
bed = 10.75
bath = 9.50

# Adapt list areas
areas = ["hallway",hall,"kitchen",kit, "living room", liv,"bedroom", bed, "bathroom", bath]

# Print areas
print(areas)

['hallway', 11.25, 'kitchen', 18.0, 'living room', 20.0, 'bedroom', 10.75, 'bathroom', 9.5]


In [12]:
# house information as list of lists
house = [["hallway", hall],
         ["kitchen", kit],
         ["living room", liv],
         ["bedroom", bed],
         ["bathroom", bath]]

# Print out house
print(house)

# Print out the type of house
print(type(house))

[['hallway', 11.25], ['kitchen', 18.0], ['living room', 20.0], ['bedroom', 10.75], ['bathroom', 9.5]]
<class 'list'>


# subsetting lists

In [13]:
# Create the areas list
areas = ["hallway", 11.25, "kitchen", 18.0, "living room", 20.0, "bedroom", 10.75, "bathroom", 9.50]

# Print out second element from areas
print(areas[1])

# Print out last element from areas
print(areas[-1])

# Print out the area of the living room
print(areas[5])

11.25
9.5
20.0


In [14]:
# Sum of kitchen and bedroom area: eat_sleep_area
eat_sleep_area=areas[3]+areas[7]

# Print the variable eat_sleep_area
print(eat_sleep_area)

28.75


# slicing and dicing lists

In [15]:
# Use slicing to create downstairs
downstairs=areas[0:6]

# Use slicing to create upstairs
upstairs=areas[6:10]

# Print out downstairs and upstairs
print(downstairs)
print(upstairs)

['hallway', 11.25, 'kitchen', 18.0, 'living room', 20.0]
['bedroom', 10.75, 'bathroom', 9.5]


In [16]:
# Alternative slicing to create downstairs
downstairs=areas[:6]

# Alternative slicing to create upstairs
upstairs=areas[6:]
# Print out downstairs and upstairs
print(downstairs)
print(upstairs)

['hallway', 11.25, 'kitchen', 18.0, 'living room', 20.0]
['bedroom', 10.75, 'bathroom', 9.5]


# manipulating lists

In [17]:
# Correct the bathroom area
areas[-1]=10.50

# Change "living room" to "chill zone"
areas[4]="chill zone"

print(areas)

['hallway', 11.25, 'kitchen', 18.0, 'chill zone', 20.0, 'bedroom', 10.75, 'bathroom', 10.5]


In [18]:
# Add poolhouse data to areas, new list is areas_1
areas_1=areas+["poolhouse",24.5]

# Add garage data to areas_1, new list is areas_2
areas_2=areas_1+["garage",15.45]

print(areas_1)
print(areas_2)

['hallway', 11.25, 'kitchen', 18.0, 'chill zone', 20.0, 'bedroom', 10.75, 'bathroom', 10.5, 'poolhouse', 24.5]
['hallway', 11.25, 'kitchen', 18.0, 'chill zone', 20.0, 'bedroom', 10.75, 'bathroom', 10.5, 'poolhouse', 24.5, 'garage', 15.45]


In [19]:
# deletion of chillzone
del(areas[4:6])
print(areas)

['hallway', 11.25, 'kitchen', 18.0, 'bedroom', 10.75, 'bathroom', 10.5]


# functions

In [20]:
# Create variables var1 and var2
var1 = [1, 2, 3, 4]
var2 = True

# Print out type of var1

print(type(var1))
# Print out length of var1
print(len(var1))

# Convert var2 to an integer: out2
out2=int(var2)

<class 'list'>
4


In [23]:
# help in python
help(sorted)

Help on built-in function sorted in module builtins:

sorted(iterable, /, *, key=None, reverse=False)
    Return a new list containing all items from the iterable in ascending order.
    
    A custom key function can be supplied to customize the sort order, and the
    reverse flag can be set to request the result in descending order.



In [25]:
# Create lists first and second
first = [11.25, 18.0, 20.0]
second = [10.75, 9.50]

# Paste together first and second: full
full=first+second

# Sort full in descending order: full_sorted
full_sorted=sorted(full,key=None,reverse=True)


# Print out full_sorted
print(full)
print(full_sorted)

[11.25, 18.0, 20.0, 10.75, 9.5]
[20.0, 18.0, 11.25, 10.75, 9.5]


# methods
functions which belong to objects

In [ ]:
help(str)   #lists the string methods

In [27]:
# string to experiment with: place
place = "poolhouse"

# Use upper() on place: place_up
place_up=place.upper()

# Print out place and place_up
print(place)
print(place_up)

# Print out the number of o's in place
print(place.count("o"))

poolhouse
POOLHOUSE
3


In [28]:
# list methods
# Create list areas
areas = [11.25, 18.0, 20.0, 10.75, 9.50]

# Print out the index of the element 20.0

print(areas.index(20.0))
# Print out how often 9.50 appears in areas
print(areas.count(9.50))

2
1


In [29]:
# Use append twice to add poolhouse and garage size
areas.append(24.5)
areas.append(15.45)

# Print out areas
print(areas)

# Reverse the orders of the elements in areas
areas.reverse()
# Print out areas
print(areas)

[11.25, 18.0, 20.0, 10.75, 9.5, 24.5, 15.45]
[15.45, 24.5, 9.5, 10.75, 20.0, 18.0, 11.25]


# packages

In [30]:
#math package
# Definition of radius
r = 0.43

# Import the math package
import math 

# Calculate C
C = 2*math.pi*r

# Calculate A
A = math.pi*r**2

# Build printout
print("Circumference: " + str(C))
print("Area: " + str(A))

Circumference: 2.701769682087222
Area: 0.5808804816487527


In [ ]:
# selective import
# Definition of radius
r = 192500

# Import radians function of math package
from math import radians

# Travel distance of Moon over 12 degrees. Store in dist.
dist=r*radians(12)
# Print out dist
print(dist)


# Numpy

In [33]:
height = [1.73, 1.68, 1.71, 1.89, 1.79]
weight = [65.4, 59.2, 63.6, 88.4, 68.7]
print(height)
print(weight)

[1.73, 1.68, 1.71, 1.89, 1.79]
[65.4, 59.2, 63.6, 88.4, 68.7]


In [34]:
weight / height ** 2

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

In [37]:
# import numpy
# calulation over entire array and fast.
# numpy array contain only one type unlike lists
import numpy as np
ht = np.array(height)
wt = np.array(weight)
bmi=wt/ht**2
print(bmi)

[21.85171573 20.97505669 21.75028214 24.7473475  21.44127836]


In [38]:
python_list = [1, 2, 3]
numpy_array = np.array([1, 2, 3])

In [39]:
print(python_list+python_list)
print(numpy_array+numpy_array)

[1, 2, 3, 1, 2, 3]
[2 4 6]


In [67]:
# light weight players
# height and weight are available as a regular lists

import pandas as pd
# Import numpy
import numpy as np

baseball=pd.read_csv("baseball.csv")
b_height=np.array(baseball['Height'])
b_weight=np.array(baseball['Weight'])

# Calculate the BMI: bmi
np_height_m = np.array(b_height) * 0.0254
np_weight_kg = np.array(b_weight) * 0.453592
bmi = np_weight_kg / np_height_m ** 2

# Create the light array
light = bmi < 21

# Print out light
print(light)


# Print out BMIs of all baseball players whose BMI is below 21
print(bmi[bmi < 21])



[False False False ... False False False]
[20.54255679 20.54255679 20.69282047 20.69282047 20.34343189 20.34343189
 20.69282047 20.15883472 19.4984471  20.69282047 20.9205219 ]


# subsetting numpy arrays

In [68]:
# Print out the weight at index 50
print(b_weight[50])

# Print out sub-array of np_height_in: index 100 up to and including index 110
print(b_height[100:111])

200
[73 74 72 73 69 72 73 75 75 73 72]


# 2d arrays

In [54]:
# Create baseball, a list of lists
baseball1 = [[180, 78.4],
            [215, 102.7],
            [210, 98.5],
            [188, 75.2]]

# Import numpy
import numpy as np

# Create a 2D numpy array from baseball: np_baseball
np_baseball1=np.array(baseball1)

# Print out the type of np_baseball

print(type(np_baseball1))
# Print out the shape of np_baseball
print(np_baseball1.shape)

<class 'numpy.ndarray'>
(4, 2)


In [71]:
np_baseball =np.column_stack((b_height,b_weight))
type(np_baseball)


numpy.ndarray

In [72]:
#subsetting 2d numpy arrays

# Print out the 50th row of np_baseball
print(np_baseball [49,:])

# Select the entire second column of np_baseball: np_weight_lb
np_weight_lb = np_baseball[:,1]

# Print out height of 124th player
print(np_baseball[123,0])


[ 70 195]
75


In [74]:
# 2d arithmetic
# Create numpy array: conversion
conversion=np.array([0.0254,0.453592])

# Print out product of np_baseball and conversion
print(np_baseball * conversion)

[[ 1.8796  81.64656]
 [ 1.8796  97.52228]
 [ 1.8288  95.25432]
 ...
 [ 1.905   92.98636]
 [ 1.905   86.18248]
 [ 1.8542  88.45044]]


# numpy basic stats

In [79]:
# Import numpy
import numpy as np

# Print mean height (first column)
avg = np.mean(np_baseball[:,0])
print("Average: " + str(avg))

# Print median height. Replace 'None'
med = np.median(np_baseball[:,0])
print("Median: " + str(med))

# Print out the standard deviation on height. Replace 'None'
stddev = np.std(np_baseball[:,0])
print("Standard Deviation: " + str(stddev))

# Print out correlation between first and second column. Replace 'None'
corr = np.corrcoef(np_baseball[:,0],np_baseball[:,1])
print("Correlation: " + str(corr))

Average: 73.6896551724138
Median: 74.0
Standard Deviation: 2.312791881046546
Correlation: [[1.         0.53153932]
 [0.53153932 1.        ]]
