<a href="https://colab.research.google.com/github/shrud8817/Python-Codes-Apps/blob/master/py_playground.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import numpy as np
height = np.round(np.random.normal(1.75, 0.20, 5000), 2)
weight = np.round(np.random.normal(60.32, 15, 5000), 2)

In [6]:
np_city = np.column_stack((height, weight))

In [7]:
print(np_city)

[[ 1.77 46.07]
 [ 1.78 30.73]
 [ 1.59 74.82]
 ...
 [ 1.99 47.76]
 [ 1.76 48.07]
 [ 1.85 53.72]]


In [10]:
# Addition, subtraction
print(5 + 5)
print(5 - 5)

# Multiplication, division, modulo, and exponentiation
print(3 * 5)
print(10 / 2)
print(18 % 7)
print(4 ** 2)

10
0
15
5.0
4
16


In [12]:
# Create lists first and second
first = [11.25, 18.0, 20.0]
second = [10.75, 9.50]

# Paste together first and second: full
full=first+second

# Sort full in descending order: full_sorted

full_sorted=sorted(full,reverse=True)   # sorting lists
# Print out full_sorted
print(full)
print(full_sorted)

[11.25, 18.0, 20.0, 10.75, 9.5]
[20.0, 18.0, 11.25, 10.75, 9.5]


In [13]:
# string to experiment with: place
place = "poolhouse"

# Use upper() on place: place_up
place_up=place.upper()

# Print out place and place_up
print(place)
print(place_up)

# Print out the number of o's in place
print(place.count('o'))

poolhouse
POOLHOUSE
3


In [14]:
# Create list areas
areas = [11.25, 18.0, 20.0, 10.75, 9.50]

# Print out the index of the element 20.0
print(areas.index(20.0))

# Print out how often 9.50 appears in areas

print(areas.count(9.50))

2
1


In [15]:
areas.append(24.5)
areas.append(15.45)

# Print out areas
print(areas)

# Reverse the orders of the elements in areas
areas.reverse()

# Print out areas
print(areas)

[11.25, 18.0, 20.0, 10.75, 9.5, 24.5, 15.45]
[15.45, 24.5, 9.5, 10.75, 20.0, 18.0, 11.25]


In [17]:
np_height = np.array([1.73, 1.68, 1.71, 1.89, 1.79])
np_weight = np.array([65.4, 59.2, 63.6, 88.4, 68.7])
bmi = np_weight / np_height ** 2
print(bmi)

for val in bmi :
  print(val)

[21.85171573 20.97505669 21.75028214 24.7473475  21.44127836]
21.85171572722109
20.97505668934241
21.750282138093777
24.74734749867025
21.44127836209856


In [19]:
np_height = np.array([1.73, 1.68, 1.71, 1.89, 1.79])
np_weight = np.array([65.4, 59.2, 63.6, 88.4, 68.7])
meas = np.array([np_height, np_weight])
for val in meas :
  print(val)

[1.73 1.68 1.71 1.89 1.79]
[65.4 59.2 63.6 88.4 68.7]


In [20]:
for val in np.nditer(meas) :   # 2d numpy arrays
  print(val)

1.73
1.68
1.71
1.89
1.79
65.4
59.2
63.6
88.4
68.7


In [34]:
import pandas as pd
brics=pd.read_csv("brics.csv", index_col=0)
print(brics)

         country    capital    area  population
BR        Brazil   Brasilia   8.516      200.40
RU        Russia     Moscow  17.100      143.50
IN         India  New Delhi   3.286     1252.00
CH         China    Beijing   9.597     1357.00
SA  South Africa   Pretoria   1.221       52.98


In [35]:
for lab,row in brics.iterrows():
  print(lab)
  print(row)

BR
country         Brazil
capital       Brasilia
area             8.516
population       200.4
Name: BR, dtype: object
RU
country       Russia
capital       Moscow
area            17.1
population     143.5
Name: RU, dtype: object
IN
country           India
capital       New Delhi
area              3.286
population         1252
Name: IN, dtype: object
CH
country         China
capital       Beijing
area            9.597
population       1357
Name: CH, dtype: object
SA
country       South Africa
capital           Pretoria
area                 1.221
population           52.98
Name: SA, dtype: object


In [36]:
for lab, row in brics.iterrows():
  print(lab + ": " + row["capital"])

BR: Brasilia
RU: Moscow
IN: New Delhi
CH: Beijing
SA: Pretoria


In [37]:
# add column
for lab, row in brics.iterrows() :
# - Creating Series on every iteration
  brics.loc[lab, "name_length"] = len(row["country"])
  print(brics)

         country    capital    area  population  name_length
BR        Brazil   Brasilia   8.516      200.40          6.0
RU        Russia     Moscow  17.100      143.50          NaN
IN         India  New Delhi   3.286     1252.00          NaN
CH         China    Beijing   9.597     1357.00          NaN
SA  South Africa   Pretoria   1.221       52.98          NaN
         country    capital    area  population  name_length
BR        Brazil   Brasilia   8.516      200.40          6.0
RU        Russia     Moscow  17.100      143.50          6.0
IN         India  New Delhi   3.286     1252.00          NaN
CH         China    Beijing   9.597     1357.00          NaN
SA  South Africa   Pretoria   1.221       52.98          NaN
         country    capital    area  population  name_length
BR        Brazil   Brasilia   8.516      200.40          6.0
RU        Russia     Moscow  17.100      143.50          6.0
IN         India  New Delhi   3.286     1252.00          5.0
CH         China    Beij