<a href="https://colab.research.google.com/github/shrud8817/Python-Codes-Apps/blob/master/Python%20Programming/Intermediate%20Python/intermediate_python_pandas_df.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

dictionaries

In [1]:
world = {"afghanistan":30.55, "albania":2.77, "algeria":39.21}
world["albania"]

2.77

In [2]:
world["sealand"] = 0.000027
world

{'afghanistan': 30.55, 'albania': 2.77, 'algeria': 39.21, 'sealand': 2.7e-05}

In [3]:
"sealand" in world

True

In [4]:
del(world["sealand"])
world

{'afghanistan': 30.55, 'albania': 2.77, 'algeria': 39.21}

In [7]:
dict = {
"country":["Brazil", "Russia", "India", "China", "South Africa"],
"capital":["Brasilia", "Moscow", "New Delhi", "Beijing", "Pretoria"],
"area":[8.516, 17.10, 3.286, 9.597, 1.221],
"population":[200.4, 143.5, 1252, 1357, 52.98] }

In [8]:
import pandas as pd

In [14]:
brics = pd.DataFrame(dict)
brics.index = ["BR", "RU", "IN", "CH", "SA"]
brics

country    capital    area  population
BR        Brazil   Brasilia   8.516      200.40
RU        Russia     Moscow  17.100      143.50
IN         India  New Delhi   3.286     1252.00
CH         China    Beijing   9.597     1357.00
SA  South Africa   Pretoria   1.221       52.98

In [13]:
brics=pd.read_csv("brics.csv",index_col=0)
brics.head(5)

country    capital    area  population
BR        Brazil   Brasilia   8.516      200.40
RU        Russia     Moscow  17.100      143.50
IN         India  New Delhi   3.286     1252.00
CH         China    Beijing   9.597     1357.00
SA  South Africa   Pretoria   1.221       52.98

In [ ]:
brics["country"]

BR          Brazil
RU          Russia
IN           India
CH           China
SA    South Africa
Name: country, dtype: object

In [ ]:
print(type(brics["country"]))

<class 'pandas.core.series.Series'>


In [ ]:
brics[["country"]]

country
BR        Brazil
RU        Russia
IN         India
CH         China
SA  South Africa

In [ ]:
print(type(brics[["country"]]))

<class 'pandas.core.frame.DataFrame'>


In [ ]:
#column access
brics[["country", "capital"]]

country    capital
BR        Brazil   Brasilia
RU        Russia     Moscow
IN         India  New Delhi
CH         China    Beijing
SA  South Africa   Pretoria

In [ ]:
#row access
brics[1:4]

country    capital    area  population
RU  Russia     Moscow  17.100       143.5
IN   India  New Delhi   3.286      1252.0
CH   China    Beijing   9.597      1357.0

In [ ]:
#loc (label-based)
#iloc (integer position based)
brics.loc["RU"]


<class 'pandas.core.series.Series'>


In [ ]:
brics.loc[["RU"]]

country capital  area  population
RU  Russia  Moscow  17.1       143.5

In [ ]:
print(type(brics.loc["RU"]))
print(type(brics.loc[["RU"]]))

<class 'pandas.core.series.Series'>
<class 'pandas.core.frame.DataFrame'>


In [ ]:
brics.loc[["RU", "IN", "CH"]]

country    capital    area  population
RU  Russia     Moscow  17.100       143.5
IN   India  New Delhi   3.286      1252.0
CH   China    Beijing   9.597      1357.0

In [ ]:
#row and column loc
brics.loc[["RU", "IN", "CH"], ["country", "capital"]]

country    capital
RU  Russia     Moscow
IN   India  New Delhi
CH   China    Beijing

In [ ]:
#all rows
brics.loc[:, ["country", "capital"]]

country    capital
BR        Brazil   Brasilia
RU        Russia     Moscow
IN         India  New Delhi
CH         China    Beijing
SA  South Africa   Pretoria

In [ ]:
brics.iloc[1]

country       Russia
capital       Moscow
area            17.1
population     143.5
Name: RU, dtype: object

In [ ]:
brics.iloc[[1]]

country capital  area  population
RU  Russia  Moscow  17.1       143.5

In [ ]:
brics.iloc[[1,2,3]]

country    capital    area  population
RU  Russia     Moscow  17.100       143.5
IN   India  New Delhi   3.286      1252.0
CH   China    Beijing   9.597      1357.0

In [ ]:
# row and column iloc
brics.iloc[[1,2,3], [0, 1]]

country    capital
RU  Russia     Moscow
IN   India  New Delhi
CH   China    Beijing

In [ ]:
brics.iloc[:, [0,1]]

country    capital
BR        Brazil   Brasilia
RU        Russia     Moscow
IN         India  New Delhi
CH         China    Beijing
SA  South Africa   Pretoria

comparison operators

In [15]:
import numpy as np
np_height = np.array([1.73, 1.68, 1.71, 1.89, 1.79])
np_weight = np.array([65.4, 59.2, 63.6, 88.4, 68.7])
bmi = np_weight / np_height ** 2
bmi

array([21.85171573, 20.97505669, 21.75028214, 24.7473475 , 21.44127836])

In [16]:
bmi>23

array([False, False, False,  True, False])

In [17]:
bmi[bmi>23]

array([24.7473475])

boolean operators - and, or, not

In [22]:
print(True and True)
print(True and False)
print(True or False)
print(not True)

True
False
True
False


Numpy - logical_and, logical_or, logical_not

In [19]:
np.logical_and(bmi > 21, bmi < 22)

array([ True, False,  True, False,  True])

In [ ]:
#select countries with area over 8 million km2
brics[brics["area"]>8]

country   capital    area  population
BR  Brazil  Brasilia   8.516       200.4
RU  Russia    Moscow  17.100       143.5
CH   China   Beijing   9.597      1357.0

In [ ]:
import numpy as np
brics[np.logical_and(brics["area"] > 8, brics["area"] < 10)]

country   capital   area  population
BR  Brazil  Brasilia  8.516       200.4
CH   China   Beijing  9.597      1357.0

conditionals

In [23]:
z = 4
if z % 2 == 0 : 
    print("z is even")

z is even


In [25]:
z = 6
if z % 2 == 0 :
    print("z is divisible by 2") # True
elif z % 3 == 0 :
    print("z is divisible by 3") # Never reached
else :
    print("z is neither divisible by 2 nor by 3")

z is divisible by 2


Filtering Pandas Dataframe

In [27]:
brics[brics['area']>8]

country   capital    area  population
BR  Brazil  Brasilia   8.516       200.4
RU  Russia    Moscow  17.100       143.5
CH   China   Beijing   9.597      1357.0

In [29]:
brics[np.logical_and(brics["area"] > 8, brics["area"] < 10)]

country   capital   area  population
BR  Brazil  Brasilia  8.516       200.4
CH   China   Beijing  9.597      1357.0

In [30]:
# while loop
error = 50.0

while error > 1: # True
    error = error / 4
    print(error)

12.5
3.125
0.78125


In [32]:
# for loop
fam = [1.73, 1.68, 1.71, 1.89]
for height in fam :
    print(height)

1.73
1.68
1.71
1.89


In [33]:
# enumerate
fam = [1.73, 1.68, 1.71, 1.89]
for index, height in enumerate(fam) :
    print("index " + str(index) + ": " + str(height))

index 0: 1.73
index 1: 1.68
index 2: 1.71
index 3: 1.89


In [35]:
# loop over string
for c in "family" :
    print(c.capitalize())

F
A
M
I
L
Y


In [37]:
# loop over a dictionary
world = { "afghanistan":30.55,
"albania":2.77,
"algeria":39.21 }

for key, value in world.items() :
    print(key + " -- " + str(value))

afghanistan -- 30.55
albania -- 2.77
algeria -- 39.21


In [55]:
# loop 1d arrays
np_height = np.array([74, 74, 72, 75, 75, 73])
for x in np_height:
    print (str(x)+" inches")

74 inches
74 inches
72 inches
75 inches
75 inches
73 inches


In [56]:
# looping over 2d numpy arrays

import numpy as np
np_height = np.array([1.73, 1.68, 1.71, 1.89, 1.79])
np_weight = np.array([65.4, 59.2, 63.6, 88.4, 68.7])
#meas = np.row_stack((np_height,np_weight))
meas = np.array([np_height, np_weight])
meas

array([[ 1.73,  1.68,  1.71,  1.89,  1.79],
       [65.4 , 59.2 , 63.6 , 88.4 , 68.7 ]])

In [48]:
for val in meas :
    print(val)

[1.73 1.68 1.71 1.89 1.79]
[65.4 59.2 63.6 88.4 68.7]


In [49]:
for val in np.nditer(meas) :
    print(val)

1.73
1.68
1.71
1.89
1.79
65.4
59.2
63.6
88.4
68.7


In [50]:
# looping dataframes
for val in brics:
    print(val)

country
capital
area
population


In [51]:
for lab,row in brics.iterrows():
    print(lab)
    print(row)

BR
country         Brazil
capital       Brasilia
area             8.516
population       200.4
Name: BR, dtype: object
RU
country       Russia
capital       Moscow
area            17.1
population     143.5
Name: RU, dtype: object
IN
country           India
capital       New Delhi
area              3.286
population       1252.0
Name: IN, dtype: object
CH
country         China
capital       Beijing
area            9.597
population     1357.0
Name: CH, dtype: object
SA
country       South Africa
capital           Pretoria
area                 1.221
population           52.98
Name: SA, dtype: object


In [52]:
#selective print
for lab,row in brics.iterrows():
    print(lab+": "+row["capital"])

BR: Brasilia
RU: Moscow
IN: New Delhi
CH: Beijing
SA: Pretoria


In [53]:
#add columns
for lab,row in brics.iterrows():
    brics.loc[lab,"name_length"]=len(row["country"])

print(brics)

         country    capital    area  population  name_length
BR        Brazil   Brasilia   8.516      200.40          6.0
RU        Russia     Moscow  17.100      143.50          6.0
IN         India  New Delhi   3.286     1252.00          5.0
CH         China    Beijing   9.597     1357.00          5.0
SA  South Africa   Pretoria   1.221       52.98         12.0


In [54]:
#apply
brics["name_length1"]=brics["country"].apply(len)
print(brics)

         country    capital    area  population  name_length  name_length1
BR        Brazil   Brasilia   8.516      200.40          6.0             6
RU        Russia     Moscow  17.100      143.50          6.0             6
IN         India  New Delhi   3.286     1252.00          5.0             5
CH         China    Beijing   9.597     1357.00          5.0             5
SA  South Africa   Pretoria   1.221       52.98         12.0            12


Practice

In [1]:
# Import cars data
import pandas as pd
cars = pd.read_csv('cars.csv', index_col = 0)

# Import numpy, you'll need this
import numpy as np

# Create medium: observations with cars_per_cap between 100 and 500

cpc = cars['cars_per_cap']
between = np.logical_and(cpc>100, cpc<500)
medium = cars[between]


# Print medium
print(cpc)
print(between)
print(medium)

US     809
AUS    731
JAP    588
IN      18
RU     200
MOR     70
EG      45
Name: cars_per_cap, dtype: int64
US     False
AUS    False
JAP    False
IN     False
RU      True
MOR    False
EG     False
Name: cars_per_cap, dtype: bool
    cars_per_cap country  drives_right
RU           200  Russia          True


In [57]:
# Import cars data
import pandas as pd
cars = pd.read_csv('cars.csv', index_col = 0)

# Code for loop that adds COUNTRY column
for lab,row in cars.iterrows():
    cars.loc[lab,"COUNTRY"] = row["country"].upper()


# Print cars
print(cars)

     cars_per_cap        country  drives_right        COUNTRY
US            809  United States          True  UNITED STATES
AUS           731      Australia         False      AUSTRALIA
JAP           588          Japan         False          JAPAN
IN             18          India         False          INDIA
RU            200         Russia          True         RUSSIA
MOR            70        Morocco          True        MOROCCO
EG             45          Egypt          True          EGYPT


In [58]:
# Import cars data
import pandas as pd
cars = pd.read_csv('cars.csv', index_col = 0)

# Use .apply(str.upper)

cars["COUNTRY"] = cars["country"].apply(str.upper)
print(cars)

     cars_per_cap        country  drives_right        COUNTRY
US            809  United States          True  UNITED STATES
AUS           731      Australia         False      AUSTRALIA
JAP           588          Japan         False          JAPAN
IN             18          India         False          INDIA
RU            200         Russia          True         RUSSIA
MOR            70        Morocco          True        MOROCCO
EG             45          Egypt          True          EGYPT
